package edu.fcle.proyectogoogle.model.bean;

// Generated 12/08/2010 09:38:35 PM by Hibernate Tools 3.3.0.GA

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idCliente;
	private String usuarioCliente;
	private String claveCliente;
	private String apepatCliente;
	private String apematCliente;
	private String nombresCliente;

	public Cliente() {
	}

	public Cliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente(int idCliente, String usuarioCliente, String claveCliente,
			String apepatCliente, String apematCliente, String nombresCliente) {
		this.idCliente = idCliente;
		this.usuarioCliente = usuarioCliente;
		this.claveCliente = claveCliente;
		this.apepatCliente = apepatCliente;
		this.apematCliente = apematCliente;
		this.nombresCliente = nombresCliente;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public String getUsuarioCliente() {
		return this.usuarioCliente;
	}

	public void setUsuarioCliente(String usuarioCliente) {
		this.usuarioCliente = usuarioCliente;
	}

	public String getClaveCliente() {
		return this.claveCliente;
	}

	public void setClaveCliente(String claveCliente) {
		this.claveCliente = claveCliente;
	}

	public String getApepatCliente() {
		return this.apepatCliente;
	}

	public void setApepatCliente(String apepatCliente) {
		this.apepatCliente = apepatCliente;
	}

	public String getApematCliente() {
		return this.apematCliente;
	}

	public void setApematCliente(String apematCliente) {
		this.apematCliente = apematCliente;
	}

	public String getNombresCliente() {
		return this.nombresCliente;
	}

	public void setNombresCliente(String nombresCliente) {
		this.nombresCliente = nombresCliente;
	}

}
